version: '3'

services:
  node:
    container_name: 'node-nest'
    build: .
    env_file:
      - ./packages/server/.dev.env
      - ./packages/server/.prod.env
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: 'mysql'
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: buddah159
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  nginx:
    container_name: 'nginx'
    build: ./packages/nginx
    ports:
      - 3000:3000
    volumes:
      - ./packages/nginx/configs:/etc/nginx
      - ./packages/client/build:/usr/share/buddah-client

volumes:
  mysql-volume:
    external: true
    name: mysql-volume
